version: "3.9"

services:
  app1:
    image: myapp:latest
    container_name: myapp1
    networks:
      - mynet

  app2:
    image: myapp:latest
    container_name: myapp2
    networks:
      - mynet

  nginx:
    image: nginx:latest
    container_name: nginx-lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
