version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"



#docker-compose -f ./kafka.yaml up -d
#docker-compose up -d ./kafka.yaml
#docker stop $(docker ps -aq)
#wsl --unregister Ubuntu-22.04

#docker rm -f $(docker ps -aq)
#docker volume rm $(docker volume ls -q)
#docker network rm $(docker network ls -q)
#docker rmi -f $(docker images -q)
#docker system prune -a --volumes -f
#docker exec -it kafka /opt/bitnami/kafka/bin/kafka-topics.sh --create  --topic test-topic --bootstrap-server localhost:9092  --partitions 1  --replication-factor 1
# docker exec -it kafka /opt/bitnami/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092
