services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER   # 🔑 cái này bị thiếu nên bạn mới lỗi


#docker-compose -f ./kafka.yaml up -d
#docker-compose up -d ./kafka.yaml
#docker stop $(docker ps -aq)
#wsl --unregister Ubuntu-22.04

#docker rm -f $(docker ps -aq)
#docker volume rm $(docker volume ls -q)
#docker network rm $(docker network ls -q)
#docker rmi -f $(docker images -q)
#docker system prune -a --volumes -f
#docker exec -it kafka /opt/bitnami/kafka/bin/kafka-topics.sh --create  --topic test-topic --bootstrap-server localhost:9092  --partitions 1  --replication-factor 1
# docker exec -it kafka /opt/bitnami/kafka/bin/kafka-topics.sh --list --bootstrap-server localhost:9092
