package jwt

import (
	"core/models"
	"core/services/aes"
	"core/services/cacher"
	"core/services/errs"
	"crypto/rand"
	"encoding/base64"
	"strings"
	"sync"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

type JwtService struct {
	cache cacher.CacheService
	errs.ErrService
	aes.AesService
}

type TokenInfo struct {
	Token string
	//Bearer or ...
	TokenType string
}
type initExtractToken struct {
	val  *TokenInfo
	err  error
	once sync.Once
}

var initExtractTokenMap sync.Map

func (jwtSvc *JwtService) ExtractToken(authorization string) (*TokenInfo, error) {
	a, _ := initExtractTokenMap.LoadOrStore(authorization, &initExtractToken{})
	i := a.(*initExtractToken)
	i.once.Do(func() {
		items := strings.Split(authorization, " ")
		if len(items) < 2 {
			i.err = jwtSvc.ErrService.BadRequest("invalid token")
		}
		i.val = &TokenInfo{
			Token:     items[1],
			TokenType: items[0],
		}
	})
	if i.err != nil {
		initExtractTokenMap.Delete(authorization)
		return i.val, i.err
	}
	return i.val, i.err

}

func NewJwtService() *JwtService {
	return &JwtService{}
}

// GenerateSecret generates a random secret with length n bytes
// and returns it as a Base64 URL-safe string (no padding).
// Recommended size: at least 32 bytes (256 bits).
func (jwtSvc *JwtService) GenerateSecret(SecretLen int) (string, error) {
	// if n <= 0 {
	// 	return "", errors.New("n must be > 0")
	// }
	if SecretLen <= 0 {
		SecretLen = 32
	}
	b := make([]byte, SecretLen)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	// Use RawURLEncoding so it's safe for headers/URLs and has no '=' padding
	return base64.RawURLEncoding.EncodeToString(b), nil
}

// NewJWTWithSecret creates a JWT token signed with HS256 using the provided secret.
// `secret` should be a Base64 URL-encoded string (generated by GenerateSecret).
func (jwtSvc *JwtService) NewJWTWithSecret(secret, Issuer string, account *models.SysUsers, ttl time.Duration) (string, error) {
	claims := IndentifierClaims{}
	//claims.Subject = account.Id
	claims.IssuedAt = jwt.NewNumericDate(time.Now())
	claims.ExpiresAt = jwt.NewNumericDate(time.Now().Add(ttl))
	//claims.Issuer = Issuer
	claims.Data = Indentifier{
		RoleId:   account.RoleId,
		Email:    account.Email,
		Tenant:   Issuer,
		UserId:   account.Id,
		Username: account.Username,
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)

	key, err := base64.RawURLEncoding.DecodeString(secret)
	if err != nil {
		return "", err
	}

	return token.SignedString(key)
}
