package jwt

import (
	"core/models"
	"core/services/cacher"
	"crypto/rand"
	"encoding/base64"
	"time"

	"github.com/golang-jwt/jwt/v5"
)

type JwtService struct {
	cache cacher.CacheService
}

func NewJwtService() *JwtService {
	return &JwtService{}
}

// GenerateSecret generates a random secret with length n bytes
// and returns it as a Base64 URL-safe string (no padding).
// Recommended size: at least 32 bytes (256 bits).
func (jwtSvc *JwtService) GenerateSecret(SecretLen int) (string, error) {
	// if n <= 0 {
	// 	return "", errors.New("n must be > 0")
	// }
	if SecretLen <= 0 {
		SecretLen = 32
	}
	b := make([]byte, SecretLen)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	// Use RawURLEncoding so it's safe for headers/URLs and has no '=' padding
	return base64.RawURLEncoding.EncodeToString(b), nil
}

// NewJWTWithSecret creates a JWT token signed with HS256 using the provided secret.
// `secret` should be a Base64 URL-encoded string (generated by GenerateSecret).
func (jwtSvc *JwtService) NewJWTWithSecret(secret, Issuer string, account *models.SysUsers, ttl time.Duration) (string, error) {
	claims := IndentifierClaims{}
	claims.Subject = account.Id
	claims.IssuedAt = jwt.NewNumericDate(time.Now())
	claims.ExpiresAt = jwt.NewNumericDate(time.Now().Add(ttl))
	claims.Issuer = Issuer
	claims.Data = Indentifier{
		RoleId: account.RoleId,
		Email:  account.Email,
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)

	key, err := base64.RawURLEncoding.DecodeString(secret)
	if err != nil {
		return "", err
	}

	return token.SignedString(key)
}
